title: Nate Meyers
description: "Data Scientist | Applied Mathematics | Problem Solver"

author:
  name: 'Nate Meyers'
  email: nathanlmeyers@gmail.com
  github_username: nathanlmeyers
  linkedin_username: natemeyers7
